server.name: kibana
server.host: 0.0.0.0
server.basePath: "/logs"
server.rewriteBasePath: true
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}
xpack.encryptedSavedObjects:
  keyRotation:
    decryptionOnlyKeys: ["iHNSfownsdfuyusef7348sdfnns8Hdhslyu&@7dshlnsdfu9ujsdfl"]
