# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: 
      - "main"
      - "actions"
  pull_request:
    branches: 
      - "main"
      - "actions"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle 8
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14.3' # Quotes required to prevent YAML converting to number
    - uses: wtfjoke/setup-groovy@v1
      with:
        groovy-version: '4.0.29'
    - name: Build with Ant
      run: |
       export GROOVY_BIN=`which groovy`
       export GROOVY_PATH=${GROOVY_BIN%/bin/groovy}
       echo $GROOVY_PATH
       mkdir -p /opt/misc/
       ln -s $GROOVY_PATH /opt/misc/groovy
       ls -l /opt/misc/
       INSTANCE=github groovy ./commons/env/PropertiesProcessor.groovy -o /opt/zfin/source_roots/zfin.org/home/WEB-INF/zfin.properties
       source commons/env/load-properties.bash
       ant do unittests
